version: '3.9'
services:
  postgres:
    image: postgres:15
    container_name: bookit_postgres
    restart: always
    environment:
      POSTGRES_USER: bookit_user
      POSTGRES_PASSWORD: bookit_pass
      POSTGRES_DB: bookit_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
